# Generated by Django 2.2.6 on 2019-10-17 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Library_Management_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='membership_fee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(max_length=10, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_Management_System.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(blank=True, max_length=50, null=True)),
                ('publication', models.CharField(max_length=50)),
                ('price', models.FloatField(null=True)),
                ('isbn', models.CharField(max_length=26, null=True)),
                ('total_books', models.IntegerField(default=1)),
                ('available', models.BooleanField(default=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_Management_System.Library')),
            ],
        ),
    ]
