# Generated by Django 2.2.6 on 2019-10-17 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Library_Management_System', '0003_remove_book_total_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='total_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField(default=datetime.datetime(2019, 10, 17, 6, 44, 48, 254870))),
                ('date_of_return', models.DateField(default=datetime.datetime(2019, 10, 24, 6, 44, 48, 254898))),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('book_borrowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_Management_System.Book')),
                ('issued_librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_Management_System.Librarian')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_Management_System.Member')),
            ],
        ),
    ]
