# Generated by Django 2.2.6 on 2019-10-17 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_Management_System', '0004_auto_20191017_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerecord',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 6, 53, 6, 70876)),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='date_of_return',
            field=models.DateField(default=datetime.datetime(2019, 10, 24, 6, 53, 6, 70904)),
        ),
    ]
