# Generated by Django 2.2.6 on 2019-10-17 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_Management_System', '0005_auto_20191017_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerecord',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 8, 24, 57, 816556)),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='date_of_return',
            field=models.DateField(default=datetime.datetime(2019, 10, 24, 8, 24, 57, 816584)),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
