# Generated by Django 2.2.6 on 2019-10-17 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_Management_System', '0006_auto_20191017_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerecord',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 10, 29, 46, 428619)),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='date_of_return',
            field=models.DateField(default=datetime.datetime(2019, 10, 24, 10, 29, 46, 428647)),
        ),
    ]
