# Generated by Django 2.2.6 on 2019-10-17 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_Management_System', '0007_auto_20191017_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerecord',
            name='fine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 10, 52, 10, 105944)),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='date_of_return',
            field=models.DateField(default=datetime.datetime(2019, 10, 24, 10, 52, 10, 105973)),
        ),
    ]
