# Generated by Django 2.2.6 on 2019-10-17 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_Management_System', '0008_auto_20191017_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuerecord',
            old_name='fine',
            new_name='penalty_per_day',
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 11, 19, 17, 305300)),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='date_of_return',
            field=models.DateField(default=datetime.datetime(2019, 10, 24, 11, 19, 17, 305327)),
        ),
    ]
